MODULES := \
	app/App \
	app/App_Win32 \
	app/File_Stream \
	app/Window \
	app/XBox \
	\
	content/Content \
	content/File_Types \
	content/Manager \
	content/Resources \
	content/VFS \
	\
	debug/Debug \
	debug/Log \
	debug/Memory \
	\
	engine/Console \
	engine/Engine \
	engine/Engine_Draw \
	\
	filesys/Filesystem \
	filesys/File_Stats \
	\
	game/Dialogue \
	game/Game \
	game/Game_Update \
	game/Map \
	game/Map_2D_Tile \
	game/Map_Height \
	\
	gl/OpenGL \
	gl/se_gl \
	gl/Shader \
	gl/Ver_110 \
	gl/Ver_300 \
	\
	gui/Button \
	gui/GUI \
	gui/Message_Log \
	\
	math/Math \
	\
	menu/Menu \
	menu/Menu_Base \
	menu/Menu_Buttons \
	menu/Menu_Internals \
	menu/Menu_Load \
	\
	module/Module \
	module/Events \
	module/Thread \
	\
	network/Client \
	network/Host \
	network/Net \
	network/Socket \
	\
	os/Bass \
	os/File \
	os/Input \
	os/Input_Codes \
	os/Threader \
	os/win32/MainWinProc \
	\
	physics/Object \
	physics/Object_Effects \
	physics/Physics \
	\
	pugixml/pugixml \
	\
	render/Font \
	render/Material \
	render/Mesh \
	render/Mesh_Load \
	render/Mesh_SMDL \
	render/Mesh_VBO \
	render/Particle_System \
	render/Texture \
	\
	ss/Survivor_Script \
	ss/ss_lib/Core \
	ss/ss_lib/Core_Funcs \
	ss/ss_lib/Core_Types \
	ss/ss_lib/Math \
	\
	utility/Draw_Utility \
	utility/Cipher \
	utility/Functions \
	utility/Lua \
	utility/MD5 \
	utility/Timer \
	utility/Utility \
	\
	stranded/Stranded_Core \
	main \
	User_Space


